# Generated by Django 2.1.2 on 2018-11-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.TextField(default='', help_text='valid url'),
        ),
    ]
