# Generated by Django 2.1.2 on 2018-11-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_post_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
