# Generated by Django 2.1.2 on 2018-11-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_number', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(blank=True, max_length=20, null=True)),
                ('l_name', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=144, null=True)),
                ('county', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('gpa', models.IntegerField(blank=True, null=True)),
                ('passwords', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
