# Generated by Django 2.1.2 on 2018-11-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20181115_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='county',
            new_name='country',
        ),
    ]
