# Generated by Django 2.1.2 on 2018-11-15 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20181116_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='dob',
            new_name='birth',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='f_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='l_name',
            new_name='last_name',
        ),
    ]
